using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Text.Json;
using PokeMacroBuilder.Models;

namespace PokeMacroBuilder.Services;

// ---- 永続化用 DTO ----
internal sealed class MacroDto
{
    public int Version { get; set; } = 2;
    public string DisplayName { get; set; } = "";
    public string Loop { get; set; } = "None";
    public int LoopCount { get; set; } = 1;
    public List<BlockDto> Blocks { get; set; } = new();
}

internal sealed class BlockDto
{
    public string Kind { get; set; } = "";
    // 入力
    public List<string>? Keys { get; set; }
    public double Duration { get; set; }
    public double Wait { get; set; }
    public int Repeat { get; set; } = 1;
    public double Seconds { get; set; }
    public int Device { get; set; }
    public int Direction { get; set; }
    public double Magnitude { get; set; } = 100;
    public int Mode { get; set; }
    public string? KeyCode { get; set; }
    // 制御
    public int LoopKind { get; set; } = 1;
    public int Count { get; set; } = 10;
    public int CondKind { get; set; }
    public string CondVar { get; set; } = "cnt";
    public int CondOp { get; set; }
    public string CondValue { get; set; } = "0";
    public string CondImageRef { get; set; } = "";
    public double CondThreshold { get; set; } = 0.8;
    public bool HasElse { get; set; }
    public List<BlockDto>? Children { get; set; }
    public List<BlockDto>? ElseChildren { get; set; }
    public List<ElseIfDto>? ElseIfs { get; set; }
    // 変数・通知
    public string VarName { get; set; } = "cnt";
    public int VarOp { get; set; }
    public string VarValue { get; set; } = "0";
    public int Channel { get; set; }
    public bool AttachScreenshot { get; set; }
    public string Text { get; set; } = "";
    public string Name { get; set; } = "";
}

internal sealed class ElseIfDto
{
    public int CondKind { get; set; }
    public string CondVar { get; set; } = "cnt";
    public int CondOp { get; set; }
    public string CondValue { get; set; } = "0";
    public string CondImageRef { get; set; } = "";
    public double CondThreshold { get; set; } = 0.8;
    public List<BlockDto> Children { get; set; } = new();
}

/// <summary>
/// MacroDocument と JSON(Base64) の相互変換。
/// 生成 .py の先頭コメント「# PMB-DATA:&lt;base64&gt;」に保存し、再読み込み時に復元する。
/// </summary>
public static class MacroSerializer
{
    public const string Marker = "# PMB-DATA:";
    public const string SignatureComment = "# Generated by PokeMacroBuilder";

    private static readonly JsonSerializerOptions JsonOpts = new() { WriteIndented = false };

    public static string ToBase64(MacroDocument doc)
    {
        var dto = new MacroDto
        {
            DisplayName = doc.DisplayName,
            Loop = doc.Loop.ToString(),
            LoopCount = doc.LoopCount,
            Blocks = doc.Blocks.Select(BuildBlock).ToList(),
        };
        var json = JsonSerializer.Serialize(dto, JsonOpts);
        return Convert.ToBase64String(Encoding.UTF8.GetBytes(json));
    }

    public static MacroDocument Clone(MacroDocument doc)
        => TryParse(Marker + ToBase64(doc)) ?? new MacroDocument { DisplayName = doc.DisplayName };

    public static MacroDocument? TryParse(string fileText)
    {
        string? base64 = null;
        foreach (var rawLine in fileText.Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.StartsWith(Marker, StringComparison.Ordinal))
            {
                base64 = line.Substring(Marker.Length).Trim();
                break;
            }
        }
        if (string.IsNullOrEmpty(base64)) return null;

        try
        {
            var json = Encoding.UTF8.GetString(Convert.FromBase64String(base64));
            var dto = JsonSerializer.Deserialize<MacroDto>(json, JsonOpts);
            if (dto is null) return null;

            var doc = new MacroDocument
            {
                DisplayName = dto.DisplayName,
                Loop = Enum.TryParse<LoopMode>(dto.Loop, out var lm) ? lm : LoopMode.None,
                LoopCount = dto.LoopCount <= 0 ? 1 : dto.LoopCount,
            };
            foreach (var b in dto.Blocks) doc.Blocks.Add(BuildModel(b));
            return doc;
        }
        catch
        {
            return null;
        }
    }

    // ---- model -> dto ----
    private static BlockDto BuildBlock(MacroBlock b)
    {
        switch (b)
        {
            case PressBlock p:
                return new BlockDto
                {
                    Kind = "press", Mode = p.Mode,
                    Keys = p.Keys.Select(k => k.SelectedKey.Code).ToList(),
                    Duration = p.Duration, Wait = p.Wait, Repeat = p.Repeat,
                };
            case StickBlock s:
                return new BlockDto
                {
                    Kind = "stick", Device = s.Device, Direction = s.Direction,
                    Magnitude = s.Magnitude, Duration = s.Duration, Wait = s.Wait,
                };
            case WaitBlock w:
                return new BlockDto { Kind = "wait", Seconds = w.Seconds };
            case LoopBlock lp:
                return new BlockDto
                {
                    Kind = "loop", LoopKind = lp.LoopKind, Count = lp.Count,
                    CondKind = lp.Condition.Kind, CondVar = lp.Condition.Var, CondOp = lp.Condition.Op,
                    CondValue = lp.Condition.Value, CondImageRef = lp.Condition.ImageRef, CondThreshold = lp.Condition.Threshold,
                    Children = lp.Children.Select(BuildBlock).ToList(),
                };
            case IfBlock ib:
                return new BlockDto
                {
                    Kind = "if",
                    CondKind = ib.Condition.Kind, CondVar = ib.Condition.Var, CondOp = ib.Condition.Op,
                    CondValue = ib.Condition.Value, CondImageRef = ib.Condition.ImageRef, CondThreshold = ib.Condition.Threshold,
                    HasElse = ib.HasElse,
                    Children = ib.Children.Select(BuildBlock).ToList(),
                    ElseChildren = ib.ElseChildren.Select(BuildBlock).ToList(),
                    ElseIfs = ib.ElseIfs.Select(br => new ElseIfDto
                    {
                        CondKind = br.Condition.Kind, CondVar = br.Condition.Var, CondOp = br.Condition.Op,
                        CondValue = br.Condition.Value, CondImageRef = br.Condition.ImageRef, CondThreshold = br.Condition.Threshold,
                        Children = br.Children.Select(BuildBlock).ToList(),
                    }).ToList(),
                };
            case VariableBlock v:
                return new BlockDto { Kind = "var", VarName = v.Name, VarOp = v.Op, VarValue = v.Value };
            case LogBlock l:
                return new BlockDto { Kind = "log", Text = l.Text };
            case NotifyBlock n:
                return new BlockDto { Kind = "notify", AttachScreenshot = n.AttachScreenshot, Text = n.Text };
            case ScreenshotBlock sc:
                return new BlockDto { Kind = "screenshot", Name = sc.Name };
            default:
                return new BlockDto { Kind = "wait", Seconds = 0 };
        }
    }

    // ---- dto -> model ----
    private static MacroBlock BuildModel(BlockDto b)
    {
        switch (b.Kind)
        {
            case "press":
                var pb = new PressBlock
                {
                    Mode = b.Mode is >= 0 and <= 2 ? b.Mode : 0,
                    Duration = b.Duration, Wait = b.Wait, Repeat = b.Repeat < 1 ? 1 : b.Repeat,
                };
                pb.Keys.Clear();
                if (b.Keys is { Count: > 0 })
                    foreach (var c in b.Keys) pb.Keys.Add(new KeySlot { SelectedKey = KeyCatalog.FromCode(c) });
                else pb.Keys.Add(new KeySlot());
                return pb;
            case "stick":
                return new StickBlock
                {
                    Device = b.Device is >= 0 and <= 2 ? b.Device : 1,
                    Direction = b.Direction is >= 0 and < 8 ? b.Direction : 0,
                    Magnitude = b.Magnitude is > 0 and <= 100 ? b.Magnitude : 100,
                    Duration = b.Duration, Wait = b.Wait,
                };
            case "loop":
                var lp = new LoopBlock { LoopKind = b.LoopKind is >= 0 and <= 2 ? b.LoopKind : 1, Count = b.Count };
                LoadCond(lp.Condition, b.CondKind, b.CondVar, b.CondOp, b.CondValue, b.CondImageRef, b.CondThreshold);
                Fill(lp.Children, b.Children);
                return lp;
            // ---- 旧形式の互換読み込み ----
            case "hold":
                var oldHold = new PressBlock { Mode = b.Mode == 1 ? 2 : 1, Wait = b.Wait };
                oldHold.Keys.Clear();
                oldHold.Keys.Add(new KeySlot { SelectedKey = KeyCatalog.FromCode(b.KeyCode) });
                return oldHold;
            case "repeat":
                var oldRep = new LoopBlock { LoopKind = 1, Count = b.Count };
                Fill(oldRep.Children, b.Children);
                return oldRep;
            case "forever":
                var oldFor = new LoopBlock { LoopKind = 0 };
                Fill(oldFor.Children, b.Children);
                return oldFor;
            case "while":
                var oldWhile = new LoopBlock { LoopKind = 2 };
                oldWhile.Condition.Var = b.CondVar; oldWhile.Condition.Op = b.CondOp; oldWhile.Condition.Value = b.CondValue;
                Fill(oldWhile.Children, b.Children);
                return oldWhile;
            case "if":
                var ifb = new IfBlock { HasElse = b.HasElse };
                LoadCond(ifb.Condition, b.CondKind, b.CondVar, b.CondOp, b.CondValue, b.CondImageRef, b.CondThreshold);
                Fill(ifb.Children, b.Children);
                Fill(ifb.ElseChildren, b.ElseChildren);
                if (b.ElseIfs != null)
                    foreach (var ed in b.ElseIfs)
                    {
                        var br = new ElseIfBranch();
                        LoadCond(br.Condition, ed.CondKind, ed.CondVar, ed.CondOp, ed.CondValue, ed.CondImageRef, ed.CondThreshold);
                        Fill(br.Children, ed.Children);
                        ifb.ElseIfs.Add(br);
                    }
                return ifb;
            case "var":
                return new VariableBlock { Name = b.VarName, Op = b.VarOp is >= 0 and <= 6 ? b.VarOp : 0, Value = b.VarValue };
            case "log":
                return new LogBlock { Text = b.Text };
            case "notify":
                return new NotifyBlock { AttachScreenshot = b.AttachScreenshot, Text = b.Text };
            case "screenshot":
                return new ScreenshotBlock { Name = b.Name };
            default:
                return new WaitBlock { Seconds = b.Seconds };
        }
    }

    private static void Fill(ObservableCollection<MacroBlock> dest, List<BlockDto>? src)
    {
        if (src is null) return;
        foreach (var c in src) dest.Add(BuildModel(c));
    }

    private static void LoadCond(Condition c, int kind, string var, int op, string value, string imageRef, double threshold)
    {
        c.Kind = kind is 0 or 1 ? kind : 0;
        c.Var = var;
        c.Op = op;
        c.Value = value;
        c.ImageRef = imageRef ?? "";
        c.Threshold = threshold is > 0 and <= 1 ? threshold : 0.8;
    }
}
