using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using PokeMacroBuilder.Models;

namespace PokeMacroBuilder.Services;

// ---- 永続化用 DTO(.py のコメントに埋め込む JSON 構造) ----
internal sealed class MacroDto
{
    public int Version { get; set; } = 1;
    public string DisplayName { get; set; } = "";
    public string Loop { get; set; } = "None";
    public int LoopCount { get; set; } = 1;
    public List<BlockDto> Blocks { get; set; } = new();
}

internal sealed class BlockDto
{
    public string Kind { get; set; } = "";          // "press" / "wait"
    public List<string>? Keys { get; set; }          // press: 押すキーのCodeリスト
    public double Duration { get; set; }
    public double Wait { get; set; }
    public double Seconds { get; set; }              // wait用
}

/// <summary>
/// MacroDocument と JSON(Base64) の相互変換。
/// 生成 .py の先頭コメント「# PMB-DATA:&lt;base64&gt;」に保存し、再読み込み時に復元する。
/// </summary>
public static class MacroSerializer
{
    public const string Marker = "# PMB-DATA:";
    public const string SignatureComment = "# Generated by PokeMacroBuilder";

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = false
    };

    public static string ToBase64(MacroDocument doc)
    {
        var dto = new MacroDto
        {
            DisplayName = doc.DisplayName,
            Loop = doc.Loop.ToString(),
            LoopCount = doc.LoopCount,
        };

        foreach (var block in doc.Blocks)
        {
            switch (block)
            {
                case PressBlock p:
                    var keys = new List<string>();
                    foreach (var slot in p.Keys) keys.Add(slot.SelectedKey.Code);
                    dto.Blocks.Add(new BlockDto
                    {
                        Kind = "press",
                        Keys = keys,
                        Duration = p.Duration,
                        Wait = p.Wait,
                    });
                    break;
                case WaitBlock w:
                    dto.Blocks.Add(new BlockDto { Kind = "wait", Seconds = w.Seconds });
                    break;
            }
        }

        var json = JsonSerializer.Serialize(dto, JsonOpts);
        return Convert.ToBase64String(Encoding.UTF8.GetBytes(json));
    }

    /// <summary>ファイル本文から MacroDocument を復元。マーカーが無ければ null。</summary>
    public static MacroDocument? TryParse(string fileText)
    {
        string? base64 = null;
        foreach (var rawLine in fileText.Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.StartsWith(Marker, StringComparison.Ordinal))
            {
                base64 = line.Substring(Marker.Length).Trim();
                break;
            }
        }
        if (string.IsNullOrEmpty(base64)) return null;

        try
        {
            var json = Encoding.UTF8.GetString(Convert.FromBase64String(base64));
            var dto = JsonSerializer.Deserialize<MacroDto>(json, JsonOpts);
            if (dto is null) return null;

            var doc = new MacroDocument
            {
                DisplayName = dto.DisplayName,
                Loop = Enum.TryParse<LoopMode>(dto.Loop, out var lm) ? lm : LoopMode.None,
                LoopCount = dto.LoopCount <= 0 ? 1 : dto.LoopCount,
            };

            foreach (var b in dto.Blocks)
            {
                if (b.Kind == "press")
                {
                    var pb = new PressBlock { Duration = b.Duration, Wait = b.Wait };
                    pb.Keys.Clear();
                    if (b.Keys is { Count: > 0 })
                    {
                        foreach (var code in b.Keys)
                            pb.Keys.Add(new KeySlot { SelectedKey = KeyCatalog.FromCode(code) });
                    }
                    else
                    {
                        pb.Keys.Add(new KeySlot());
                    }
                    doc.Blocks.Add(pb);
                }
                else if (b.Kind == "wait")
                {
                    doc.Blocks.Add(new WaitBlock { Seconds = b.Seconds });
                }
            }
            return doc;
        }
        catch
        {
            return null;
        }
    }
}
